# Generated by Django 5.2.8 on 2026-02-06 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_task_due', models.BooleanField(default=True)),
                ('email_project_updates', models.BooleanField(default=True)),
                ('email_scrum_reminders', models.BooleanField(default=True)),
                ('email_leave_status', models.BooleanField(default=True)),
                ('inapp_enabled', models.BooleanField(default=True)),
                ('inapp_task_assigned', models.BooleanField(default=True)),
                ('inapp_task_due', models.BooleanField(default=True)),
                ('inapp_project_updates', models.BooleanField(default=True)),
                ('inapp_scrum_reminders', models.BooleanField(default=True)),
                ('inapp_leave_status', models.BooleanField(default=True)),
                ('task_reminder_before_hours', models.IntegerField(default=24, help_text='Hours before due date')),
                ('scrum_reminder_time', models.TimeField(default='09:00:00', help_text='Daily scrum reminder time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_due', 'Task Due Soon'), ('task_overdue', 'Task Overdue'), ('project_update', 'Project Update'), ('scrum_reminder', 'Scrum Reminder'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('meeting_reminder', 'Meeting Reminder'), ('system', 'System Notification')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('related_task_id', models.IntegerField(blank=True, null=True)),
                ('related_project_id', models.IntegerField(blank=True, null=True)),
                ('related_scrum_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('task_due', 'Task Due'), ('scrum_daily', 'Daily Scrum'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('custom', 'Custom')], max_length=50)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('related_task_id', models.IntegerField(blank=True, null=True)),
                ('related_project_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['user', 'scheduled_time'], name='notificatio_user_id_e3015e_idx'), models.Index(fields=['is_active', 'is_sent'], name='notificatio_is_acti_851309_idx')],
            },
        ),
    ]
