# Generated by Django 5.2.8 on 2025-12-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_project_delete_crmproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operation.project')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
