# Generated by Django 5.2.8 on 2025-12-16 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='allocated_hours',
            new_name='hours_allocated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.AddField(
            model_name='project',
            name='amc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='renewal_only',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='operation.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
