# Generated by Django 5.2.8 on 2025-12-17 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_rename_allocated_hours_project_hours_allocated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., USD, INR, EUR', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Full name, e.g., US Dollar', max_length=100)),
                ('symbol', models.CharField(blank=True, help_text='e.g., $, €, ₹', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Select the currency for budget', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='operation.currency'),
        ),
    ]
