# Generated by Django 5.2.8 on 2025-12-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_currency_alter_project_currency'),
        ('operation', '0006_alter_task_options_remove_task_allocated_hours_and_more'),
    ]

    operations = [
    ]
