# Generated by Django 5.2.8 on 2026-02-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
