# Generated by Django 5.2.8 on 2026-02-04 12:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_remove_task_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of this scrum update (usually today)')),
                ('reported_status', models.CharField(blank=True, choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', help_text='Status as reported in this daily scrum', max_length=20, null=True, verbose_name='Reported Status')),
                ('morning_memo', models.TextField(blank=True, null=True, verbose_name='Morning Memo')),
                ('evening_memo', models.TextField(blank=True, null=True, verbose_name='Evening Memo / General Memo')),
                ('morning_submitted', models.BooleanField(default=False)),
                ('evening_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who actually submitted this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_entries', to=settings.AUTH_USER_MODEL, verbose_name='Employee Name')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_entries', to='operation.task')),
            ],
            options={
                'verbose_name': 'Scrum',
                'verbose_name_plural': 'Scrums',
                'ordering': ['-date', 'task__name'],
                'unique_together': {('task', 'date')},
            },
        ),
    ]
