# Generated by Django 5.2.8 on 2026-02-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_scrum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrum',
            options={'verbose_name': 'Scrum', 'verbose_name_plural': 'Scrums'},
        ),
        migrations.AlterUniqueTogether(
            name='scrum',
            unique_together=set(),
        ),
    ]
