# Generated by Django 5.2.8 on 2026-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_designation_alter_department_options_and_more'),
        ('operation', '0013_contracttype_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.AddField(
            model_name='project',
            name='involved_departments',
            field=models.ManyToManyField(blank=True, related_name='projects', to='authapp.department'),
        ),
    ]
