# Generated by Django 5.2.8 on 2026-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_remove_project_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tenor',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('one_time', 'One Time')], default='one_time', max_length=20),
        ),
    ]
