# Generated by Django 5.2.8 on 2026-03-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_project_tenor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tenor',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('one_time', 'One Time')], default='one_time', max_length=20, null=True),
        ),
    ]
