# Generated by Django 5.2.8 on 2026-04-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_alter_project_tenor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amc_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dm',
        ),
        migrations.RemoveField(
            model_name='project',
            name='renewal_only',
        ),
    ]
