# Generated by Django 5.2.8 on 2025-12-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_project_breaksession_task_worksession'),
        ('operation', '0002_project_delete_crmproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operation.project'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
