# Generated by Django 5.2.8 on 2025-12-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_task_project_alter_worksession_project_and_more'),
        ('operation', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.task'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
