# Generated by Django 5.2.8 on 2025-12-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee'),
        ('sales', '0004_alter_lead_lead_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
