# Generated by Django 5.2.8 on 2026-02-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('half_day_late', 'Half Day Late'), ('leave', 'On Leave'), ('holiday', 'Holiday')], default='absent', max_length=20, null=True),
        ),
    ]
