# Generated by Django 5.2.8 on 2026-02-04 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksession',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worksession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
