# Generated by Django 5.2.8 on 2026-03-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_worksession_approved_by_worksession_is_billable_and_more'),
        ('operation', '0013_contracttype_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.project'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.task'),
        ),
    ]
