# Generated by Django 5.2.8 on 2026-03-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_worksession_approved_by_worksession_is_billable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='lead_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20, null=True),
        ),
    ]
