# Generated by Django 5.2.8 on 2026-03-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_worksession_project_alter_worksession_task'),
        ('hr', '0009_leave_lead_comments_leave_lead_status'),
    ]

    operations = [
    ]
