# Generated by Django 5.2.8 on 2025-12-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
