# Generated by Django 5.2.8 on 2025-12-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_delete_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role or Designation', 'verbose_name_plural': 'Roles & Designations'},
        ),
    ]
