# Generated by Django 5.2.8 on 2025-12-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_role_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gmail_access_token',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gmail_refresh_token',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gmail_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
