# Generated by Django 5.2.8 on 2026-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_designation_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_residential_same',
            field=models.BooleanField(default=False, help_text='Permanent Address same as Residential Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Permanent Address', null=True),
        ),
    ]
