# Generated by Django 5.2.8 on 2026-01-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='gmail_access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='gmail_refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='gmail_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
