export const countryCodes = [
    { value: "+91", label: "+91 (India)" },
    { value: "+1", label: "+1 (USA/Canada)" },
    { value: "+44", label: "+44 (UK)" },
    { value: "+971", label: "+971 (UAE)" },
    { value: "+61", label: "+61 (Australia)" },
    { value: "+65", label: "+65 (Singapore)" },
    { value: "+49", label: "+49 (Germany)" },
    { value: "+33", label: "+33 (France)" },
    { value: "+81", label: "+81 (Japan)" },
    { value: "+86", label: "+86 (China)" },
    { value: "+7", label: "+7 (Russia)" },
    { value: "+92", label: "+92 (Pakistan)" },
    { value: "+880", label: "+880 (Bangladesh)" },
    { value: "+94", label: "+94 (Sri Lanka)" },
    { value: "+977", label: "+977 (Nepal)" },
    { value: "+60", label: "+60 (Malaysia)" },
    { value: "+63", label: "+63 (Philippines)" },
    { value: "+66", label: "+66 (Thailand)" },
    { value: "+62", label: "+62 (Indonesia)" },
    { value: "+84", label: "+84 (Vietnam)" },
    { value: "+27", label: "+27 (South Africa)" },
    { value: "+234", label: "+234 (Nigeria)" },
    { value: "+254", label: "+254 (Kenya)" },
    { value: "+20", label: "+20 (Egypt)" },
    { value: "+966", label: "+966 (Saudi Arabia)" },
    { value: "+965", label: "+965 (Kuwait)" },
    { value: "+974", label: "+974 (Qatar)" },
    { value: "+968", label: "+968 (Oman)" },
    { value: "+973", label: "+973 (Bahrain)" },
    { value: "+31", label: "+31 (Netherlands)" },
    { value: "+41", label: "+41 (Switzerland)" },
    { value: "+46", label: "+46 (Sweden)" },
    { value: "+47", label: "+47 (Norway)" },
    { value: "+45", label: "+45 (Denmark)" },
    { value: "+39", label: "+39 (Italy)" },
    { value: "+34", label: "+34 (Spain)" },
    { value: "+55", label: "+55 (Brazil)" },
    { value: "+52", label: "+52 (Mexico)" },
    { value: "+54", label: "+54 (Argentina)" },
];
